var GAME_LEVELS = [
  ["                                                                                ",
   "                                                    |     |                     ",         
   "            !yyyyy!                                                             ",
   "            vyyyyyv                                                             ",
   "             yy!yy                                                              ",
   "               v                                                   o  o         ",
   "                                                      o o                       ",
   "                                            o o    xxxxxxxxxx     xx!xx         ",
   "                                    o o    xxxxx                 xx!!!xx        ",
   "                                                                  xx|xx         ",
   "                                   xxxxx                           x x          ",
   "                        o                                                       ",
   "  xx                                o o                                         ",
   "  x                     o                                                  o x  ",
   "  x        xxxxxxxx                      xxxxx                             o x  ",
   "  x         xxxxxx      o                                         ooo      o x  ",
   "  x  @ ooo  xx  xx         q       oooooo                       xxxxx     o x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x  =x                  x=   =x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   
   
   
  ["                                                                                                                  ",
   "                                                                                                                  ",                                                                                     
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                 v                                                                                                 ",
   "                                                                                                                  ",
   "             v        v                                                                                         ",
   "                                                                                                              ",
   "                                                                                                               ",
   "                                                                                                                  ",
   "                                                                                        v       v                   ",
   "                                                                                                                  ",
   "               xxxxxx                                                                                   x        ",
   "              xx    xx                                                                x    x  x    x     x         ",
   "             xx      xx                               xxxx                                              x               ",
   "     @      xx        xx                           xxxyyyyxxx                        |      |       |   x               ",
   "    xxx   xxxx        xxxx                          xx || xx                                            x       ",
   "    x x =x         x      xx  o xx                  |      |                                       o   ox              ",
   "xxx!!!!!!x         x!!!!!!xx      xxxxxxxxxxxxxxxx                           o             o      xxxxxxx                   ",
   "xxx!!!!!!x         x!!!!!xx             |    |                            xxxxxxx       xxxxxx                          ",
   "xxx!!!!!!x         x!!!!!x=   o                                                     o         !!!!!                  ",
   "xxx!!!!!!x         x!!!!!x=                              o      o          o     xxxxxx                                        ",
   "xxx!!!!!!x         x!!!!!xx o o o      o   o   o   xxxxxxxxxxxxxxxxx= =xxxxxxx!!!!    !!!!!                                      ",
   "xxx!!!!!!x         x!!!!!!xxxxxxxxxxx              x                !!!!                                        ",
   "xxx!!!!!!x         x!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x          x       xxx                            ",
   "                                      x   x                 x          x      xvvvx                           ",
   "                                      x   x                 xxxxxxxxxxxx                                      ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x v    v    x                    x!!!x                              ",
   "                                      x   x           x                                                       ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x           x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x           x            xxx       xxx                              ",
   "                                     xx   xx      o   x                     x!!!x                             ",
   "                                      x   x      xxxxxx     x                xvx       xxxxx                 ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx          x!!!!!!!!!!!!!!x                  xvx                   ",
   "                             x xxx x x xxx xxxxx      x!!!!!!!!!!!!!!x                                        ",
   "                             x             x          xxxxxxxxxxxxxxxx                                       ",
   "                             xx           xx      xxxxx                                                       ",
   "  xxx                         x     x     xx                                                              xx  ",
   "  x x                         x    xxx    xx o                                                            xx  ",
   "  x                           x    xxx    xxxxx                                                           x   ",
   "  x                           x     |    x        o          o                                            x  ",
   "  x                           xx          x      xxxxxx   xxxxxxxxx        o                              x  ",
   "  x                                                     |           |   xxxxxxx       o                   x  ",
   "  x                xxx             o o                                             xxxxx                  x  ",
   "  x               xxxxx       xx          x                                        x!!!x                  x  ",
   "  x               oxxxo       x    xxx    x         xx        xx                    xxx                   x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xxxxx                              x  ",
   "  x      @    q     x    q    x           x!!x    x!!!!x    x!!!!x    xx   xx                             x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
